use_frameworks!


source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.2'
        end
    end
end

target 'AHFMShowPage_Example' do
  pod 'AHFMShowPage', :path => '../'


pod 'AHServiceRouter'

pod 'AHFMDataCenter'
pod 'AHFMNetworking'
pod 'AHFMDataTransformers'

pod 'AHFMServices'
pod 'AHFMModuleManager'

pod 'AHFMDownloaderManager'

pod 'AHFMShowPageManger'
pod 'AHFMShowPageServices'

pod 'AHAudioPlayer'
pod 'AHFMAudioPlayerManager'

pod 'AHFMDownloadCenter'
pod 'AHFMDownloadCenterManager'

pod 'AHFMDownloadList'
pod 'AHFMDownloadListManager'
pod 'AHFMDownloadListServices'

pod 'AHFMAudioPlayerVC'
pod 'AHFMAudioPlayerVCManager'
pod 'AHFMAudioPlayerVCServices'

pod 'AHFMEpisodeListVC'
pod 'AHFMEpisodeListVCManager'

pod 'AHFMHistoryVC'
pod 'AHFMHistoryVCManager'

pod 'AHFMEpisodeListVC'
pod 'AHFMAudioPlayerManager'

pod 'AHFMBottomPlayer'
pod 'AHFMBottomPlayerManager'
pod 'AHFMBottomPlayerServices'


  target 'AHFMShowPage_Tests' do
    inherit! :search_paths

    
  end
end
